feat(problem-solver): Verify LongestInRegion agent
ostis-apps/ostis-geography pull request #63
Opened 2022-10-29 16:11 UTC by kilativ-dotcom

Works fine

2022-10-29 19:44 UTC, NikitaZotov requested changes

2022-10-29 19:44 UTC, NikitaZotov commented on problem-solver/cxx/RiversModule/RiversModule.cpp
> +  if (!Keynodes::InitGlobal()) // exampleModule это название пространства в котором находятся агенты и другие классы которые используются для работы агентов
Remove comments, please

2022-10-29 20:01 UTC, NikitaZotov commented
Add testing examples

2022-11-09 19:33 UTC, kilativ-dotcom commented
[Отчёт](https://docs.google.com/document/d/13pHQBIXRq8oRy9ryP0788ZAkCU9WRghJVnUTrwtao2Q/edit?usp=sharing)

2022-11-11 14:28 UTC, NikitaZotov approved these changes

2022-11-11 14:28 UTC, merged